{
  "title": "DAS",
  "story": [
    {
      "type": "markdown",
      "id": "fdfbf7e774ab0847",
      "text": "Future Science implements liquid peer review using a __Decentralized Assessment System__ ([[DAS]]). DAS is a peer review system that uses an incentive model with reputation rewards and produces a quantifiable metric about the quality of the assets being assessed. "
    },
    {
      "type": "markdown",
      "id": "0cadbb17492ef771",
      "text": "- DAS has been designed specifically for assessment of assets in expertise-intensive areas, such as deep-tech.\n- DAS supports the assessment of intangible assets, such as knowledge, technology, IPR assets, and even human capital, but can be used to assess any kind of assets."
    },
    {
      "type": "paragraph",
      "id": "8492a760e9d4bbe5",
      "text": "DAS sources a consensus about the quality of assets among the domain experts through continuous peer review. "
    },
    {
      "type": "paragraph",
      "id": "05bdc7c0d2f1e2c6",
      "text": "The results of peer review then formalized into explicit metrics/indicators of the quality of the asset, and all contributors (such as asset author(s), reviewers and experts who curated reviews) are rewarded with reputation score. The contributor’s reward amount directly depends on the quality of one’s contribution."
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "DAS",
        "story": []
      },
      "date": 1619114439778
    },
    {
      "id": "fdfbf7e774ab0847",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "fdfbf7e774ab0847",
        "text": "A Decentralized Assessment System ([[DAS]]) is a peer review system that uses an incentive model with reputation rewards and produces a quantifiable metric about the quality of asset(s) being assessed. "
      },
      "date": 1619114443225
    },
    {
      "id": "0cadbb17492ef771",
      "type": "add",
      "item": {
        "type": "markdown",
        "id": "0cadbb17492ef771",
        "text": "- DAS has been designed specifically for assessment of assets in expertise-intensive areas, such as deep-tech.\n- DAS supports the assessment of intangible assets, such as knowledge, technology, IPR assets, and even human capital, but can be used to assess any kind of assets."
      },
      "after": "fdfbf7e774ab0847",
      "date": 1619114445216
    },
    {
      "id": "8492a760e9d4bbe5",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "8492a760e9d4bbe5",
        "text": "DAS sources a consensus about the quality of assets among the domain experts through continuous peer review. "
      },
      "after": "0cadbb17492ef771",
      "date": 1619114446876
    },
    {
      "id": "05bdc7c0d2f1e2c6",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "05bdc7c0d2f1e2c6",
        "text": "The results of peer review then formalized into explicit metrics/indicators of the quality of the asset, and all contributors (such as asset author(s), reviewers and experts who curated reviews) are rewarded with reputation score. The contributor’s reward amount directly depends on the quality of one’s contribution."
      },
      "after": "8492a760e9d4bbe5",
      "date": 1619114448427
    },
    {
      "type": "edit",
      "id": "fdfbf7e774ab0847",
      "item": {
        "type": "paragraph",
        "id": "fdfbf7e774ab0847",
        "text": "Future Science implements liquid peer review using a __Decentralized Assessment System__ ([[DAS]]). DAS is a peer review system that uses an incentive model with reputation rewards and produces a quantifiable metric about the quality of the assets being assessed. "
      },
      "date": 1619114533677
    },
    {
      "type": "edit",
      "id": "fdfbf7e774ab0847",
      "item": {
        "type": "markdown",
        "id": "fdfbf7e774ab0847",
        "text": "Future Science implements liquid peer review using a __Decentralized Assessment System__ ([[DAS]]). DAS is a peer review system that uses an incentive model with reputation rewards and produces a quantifiable metric about the quality of the assets being assessed. "
      },
      "date": 1619114536055
    },
    {
      "type": "fork",
      "site": "future.science",
      "date": 1644273224811
    }
  ]
}