{
  "title": "K",
  "story": [
    {
      "type": "pagefold",
      "id": "1dbcb05a56540609",
      "text": "List Indexcard K"
    },
    {
      "type": "paragraph",
      "id": "5533d22aad4e327d",
      "text": "[[Keyterm]] (within [[List Indexcards]])"
    },
    {
      "type": "paragraph",
      "id": "70e18e3045fac8ac",
      "text": "[[Knowledge]] (within [[Digital Garden]])"
    },
    {
      "type": "markdown",
      "id": "3ae6c4d835763bbe",
      "text": "- (within [[Narrative? Pattern!]])"
    },
    {
      "type": "paragraph",
      "id": "415e7900837d35ec",
      "text": "[[KWIC Index]] (within [[Typescript Locator]]) ⇒ [[Index]] "
    },
    {
      "type": "paragraph",
      "id": "54176dced8c8f953",
      "text": "[[Key–Value Pair]] (within [[Associative Array]])"
    },
    {
      "type": "paragraph",
      "id": "c93cf88cfa29bd2f",
      "text": "[[Konrad Hinsen]] (within [[Substitution]]) See: [[Term Rewriting]]"
    },
    {
      "type": "markdown",
      "id": "f0bf4ec33ecbba31",
      "text": "- [[Scientific Notations for the Digital Era]] ⇒ [[Leibniz]] ⇒ [[Leibniz in 4']] ⇒ [[Implementing Leibniz in Wiki]]\n- [[Lotka-Volterra Equations]]\n\n"
    },
    {
      "type": "paragraph",
      "id": "b60f9069eab5193c",
      "text": "[[Knowledge]] → \"know\""
    },
    {
      "type": "markdown",
      "id": "906d1ef37edc37e4",
      "text": "**[[Kerry Turner]]** See: [[Engagement vs Commitment]] (within [[ST2050]])"
    },
    {
      "type": "paragraph",
      "id": "b36d99dcb8c0341c",
      "text": "- [[Kerry's poetry]]"
    },
    {
      "type": "paragraph",
      "id": "05560528fb0944c6",
      "text": "- [[Kerry Golden Paragraph]]"
    },
    {
      "type": "paragraph",
      "id": "97095af66bb334bd",
      "text": "[[Kaiten Continuous Experience]]"
    },
    {
      "type": "paragraph",
      "id": "a05bab4de90cb14c",
      "text": "[[Körper]] Siehe: [[Form des Körpers]]"
    },
    {
      "type": "reference",
      "id": "273643917e6cb71c",
      "site": "wiki.ralfbarkow.ch",
      "slug": "k",
      "title": "K",
      "text": "End of List Indexcard"
    },
    {
      "type": "frame",
      "id": "61ecdc1aecc8e543",
      "text": "//wiki.ralfbarkow.ch/assets/pages/speed-bot/speed-bot.html\nHEIGHT 222\nSOURCE graph\nSOURCE paragraph"
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "K",
        "story": []
      },
      "date": 1706079142377
    },
    {
      "item": {
        "type": "factory",
        "id": "5533d22aad4e327d"
      },
      "id": "5533d22aad4e327d",
      "type": "add",
      "date": 1706079144200
    },
    {
      "type": "edit",
      "id": "5533d22aad4e327d",
      "item": {
        "type": "paragraph",
        "id": "5533d22aad4e327d",
        "text": "[[Keyterm] (within [[List Indexcards]])"
      },
      "date": 1706079160165
    },
    {
      "type": "edit",
      "id": "5533d22aad4e327d",
      "item": {
        "type": "paragraph",
        "id": "5533d22aad4e327d",
        "text": "[[Keyterm]] (within [[List Indexcards]])"
      },
      "date": 1706079165041
    },
    {
      "id": "1dbcb05a56540609",
      "type": "add",
      "item": {
        "type": "pagefold",
        "id": "1dbcb05a56540609",
        "text": "List Indexcard A"
      },
      "attribution": {
        "page": "A"
      },
      "date": 1706079169559
    },
    {
      "type": "edit",
      "id": "1dbcb05a56540609",
      "item": {
        "type": "pagefold",
        "id": "1dbcb05a56540609",
        "text": "List Indexcard K"
      },
      "date": 1706079174261
    },
    {
      "item": {
        "type": "factory",
        "id": "70e18e3045fac8ac"
      },
      "id": "70e18e3045fac8ac",
      "type": "add",
      "after": "5533d22aad4e327d",
      "date": 1706082042275
    },
    {
      "type": "edit",
      "id": "70e18e3045fac8ac",
      "item": {
        "type": "paragraph",
        "id": "70e18e3045fac8ac",
        "text": "[[Knowledge]] (within [[Digital Garden]])"
      },
      "date": 1706082054532
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1706084421972
    },
    {
      "type": "add",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "paragraph",
        "id": "3ae6c4d835763bbe",
        "text": "– (within [[Narrative? Pattern!]]"
      },
      "after": "70e18e3045fac8ac",
      "date": 1706084441906
    },
    {
      "type": "edit",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "paragraph",
        "id": "3ae6c4d835763bbe",
        "text": "- (within [[Narrative? Pattern!]]"
      },
      "date": 1706084454642
    },
    {
      "type": "edit",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "markdown",
        "id": "3ae6c4d835763bbe",
        "text": "- (within [[Narrative? Pattern!]]"
      },
      "date": 1706084456393
    },
    {
      "type": "edit",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "markdown",
        "id": "3ae6c4d835763bbe",
        "text": "- (within [[Narrative? Pattern!]])"
      },
      "date": 1706084463657
    },
    {
      "item": {
        "type": "factory",
        "id": "415e7900837d35ec"
      },
      "id": "415e7900837d35ec",
      "type": "add",
      "after": "3ae6c4d835763bbe",
      "date": 1706103067928
    },
    {
      "type": "edit",
      "id": "415e7900837d35ec",
      "item": {
        "type": "paragraph",
        "id": "415e7900837d35ec",
        "text": "[[KWIC Index]] "
      },
      "date": 1706103070030
    },
    {
      "type": "edit",
      "id": "415e7900837d35ec",
      "item": {
        "type": "paragraph",
        "id": "415e7900837d35ec",
        "text": "[[KWIC Index]] (within [[Typescript Locator]])"
      },
      "date": 1706103098340
    },
    {
      "type": "edit",
      "id": "415e7900837d35ec",
      "item": {
        "type": "paragraph",
        "id": "415e7900837d35ec",
        "text": "[[KWIC Index]] (within [[Typescript Locator]]) ⇒ [[Index]] "
      },
      "date": 1706103127341
    },
    {
      "item": {
        "type": "factory",
        "id": "54176dced8c8f953"
      },
      "id": "54176dced8c8f953",
      "type": "add",
      "after": "415e7900837d35ec",
      "date": 1706105668940
    },
    {
      "type": "edit",
      "id": "54176dced8c8f953",
      "item": {
        "type": "paragraph",
        "id": "54176dced8c8f953",
        "text": "key-value pairs (within [[Associative Array]])"
      },
      "date": 1706105681677
    },
    {
      "type": "edit",
      "id": "54176dced8c8f953",
      "item": {
        "type": "paragraph",
        "id": "54176dced8c8f953",
        "text": "[[Key–Value Pair]] (within [[Associative Array]])"
      },
      "date": 1706105808984
    },
    {
      "item": {
        "type": "factory",
        "id": "c93cf88cfa29bd2f"
      },
      "id": "c93cf88cfa29bd2f",
      "type": "add",
      "after": "54176dced8c8f953",
      "date": 1706199475888
    },
    {
      "type": "edit",
      "id": "c93cf88cfa29bd2f",
      "item": {
        "type": "paragraph",
        "id": "c93cf88cfa29bd2f",
        "text": "[[Konrad Hinsen]] (within [[Substituion]])"
      },
      "date": 1706199512849
    },
    {
      "type": "edit",
      "id": "c93cf88cfa29bd2f",
      "item": {
        "type": "paragraph",
        "id": "c93cf88cfa29bd2f",
        "text": "[[Konrad Hinsen]] (within [[Substitution]])"
      },
      "date": 1706199538852
    },
    {
      "type": "edit",
      "id": "c93cf88cfa29bd2f",
      "item": {
        "type": "paragraph",
        "id": "c93cf88cfa29bd2f",
        "text": "[[Konrad Hinsen]] (within [[Substitution]]) See [Term Rewriting]]"
      },
      "date": 1706199563541
    },
    {
      "type": "edit",
      "id": "c93cf88cfa29bd2f",
      "item": {
        "type": "paragraph",
        "id": "c93cf88cfa29bd2f",
        "text": "[[Konrad Hinsen]] (within [[Substitution]]) See [[Term Rewriting]]"
      },
      "date": 1706199571007
    },
    {
      "id": "f0bf4ec33ecbba31",
      "type": "add",
      "item": {
        "type": "markdown",
        "id": "f0bf4ec33ecbba31",
        "text": "[https://www.sjscience.org/memberPage?uId=90&jId=6#journal Konrad Hinsen's Self-Journal]\n- [[Scientific Notations for the Digital Era]]\n\n"
      },
      "after": "c93cf88cfa29bd2f",
      "attribution": {
        "page": "Konrad Hinsen"
      },
      "date": 1706199595014
    },
    {
      "type": "edit",
      "id": "f0bf4ec33ecbba31",
      "item": {
        "type": "markdown",
        "id": "f0bf4ec33ecbba31",
        "text": "- [[Scientific Notations for the Digital Era]]\n\n"
      },
      "date": 1706199603231
    },
    {
      "id": "2421448e1ba23e7b",
      "type": "add",
      "item": {
        "type": "markdown",
        "id": "2421448e1ba23e7b",
        "text": "⇒ [[Leibniz]]"
      },
      "after": "f0bf4ec33ecbba31",
      "attribution": {
        "page": "Konrad Hinsen"
      },
      "date": 1706199615762
    },
    {
      "type": "remove",
      "id": "2421448e1ba23e7b",
      "date": 1706199643627
    },
    {
      "type": "edit",
      "id": "f0bf4ec33ecbba31",
      "item": {
        "type": "markdown",
        "id": "f0bf4ec33ecbba31",
        "text": "- [[Scientific Notations for the Digital Era]] ⇒ [[Leibniz]]\n\n"
      },
      "date": 1706199648456
    },
    {
      "id": "f1ad97618cd2bff3",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "f1ad97618cd2bff3",
        "text": "[[Leibniz in 4']]"
      },
      "after": "f0bf4ec33ecbba31",
      "attribution": {
        "page": "L"
      },
      "date": 1706199683668
    },
    {
      "type": "remove",
      "id": "f1ad97618cd2bff3",
      "date": 1706199688228
    },
    {
      "type": "edit",
      "id": "f0bf4ec33ecbba31",
      "item": {
        "type": "markdown",
        "id": "f0bf4ec33ecbba31",
        "text": "- [[Scientific Notations for the Digital Era]] ⇒ [[Leibniz]] ⇒ [[Leibniz in 4']]\n\n"
      },
      "date": 1706199696630
    },
    {
      "id": "29699e4d42d78b4d",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "29699e4d42d78b4d",
        "text": "⇒ [[Implementing Leibniz in Wiki]]"
      },
      "after": "f0bf4ec33ecbba31",
      "attribution": {
        "page": "Leibniz in 4'"
      },
      "date": 1706199790105
    },
    {
      "type": "remove",
      "id": "29699e4d42d78b4d",
      "date": 1706199795687
    },
    {
      "type": "edit",
      "id": "f0bf4ec33ecbba31",
      "item": {
        "type": "markdown",
        "id": "f0bf4ec33ecbba31",
        "text": "- [[Scientific Notations for the Digital Era]] ⇒ [[Leibniz]] ⇒ [[Leibniz in 4']] ⇒ [[Implementing Leibniz in Wiki]]\n\n"
      },
      "date": 1706199800968
    },
    {
      "id": "2d5a10d53bc992b2",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "2d5a10d53bc992b2",
        "text": "[[Lotka-Volterra Equations]]"
      },
      "after": "f0bf4ec33ecbba31",
      "attribution": {
        "page": "L"
      },
      "date": 1706200015170
    },
    {
      "type": "remove",
      "id": "2d5a10d53bc992b2",
      "date": 1706200019537
    },
    {
      "type": "edit",
      "id": "f0bf4ec33ecbba31",
      "item": {
        "type": "markdown",
        "id": "f0bf4ec33ecbba31",
        "text": "- [[Scientific Notations for the Digital Era]] ⇒ [[Leibniz]] ⇒ [[Leibniz in 4']] ⇒ [[Implementing Leibniz in Wiki]]\n- [[Lotka-Volterra Equations]]\n\n"
      },
      "date": 1706200023781
    },
    {
      "type": "fork",
      "site": "wiki.ralfbarkow.ch",
      "date": 1706210144668
    },
    {
      "item": {
        "type": "factory",
        "id": "b60f9069eab5193c"
      },
      "id": "b60f9069eab5193c",
      "type": "add",
      "after": "f0bf4ec33ecbba31",
      "date": 1706471615159
    },
    {
      "type": "edit",
      "id": "b60f9069eab5193c",
      "item": {
        "type": "paragraph",
        "id": "b60f9069eab5193c",
        "text": "[[Knowledge]] → \"know\""
      },
      "date": 1706471630377
    },
    {
      "type": "edit",
      "id": "c93cf88cfa29bd2f",
      "item": {
        "type": "paragraph",
        "id": "c93cf88cfa29bd2f",
        "text": "[[Konrad Hinsen]] (within [[Substitution]]) See: [[Term Rewriting]]"
      },
      "date": 1706472092644
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1706474195597
    },
    {
      "id": "273643917e6cb71c",
      "type": "add",
      "item": {
        "type": "reference",
        "id": "273643917e6cb71c",
        "site": "wiki.ralfbarkow.ch",
        "slug": "k",
        "title": "K",
        "text": "End of List Indexcard"
      },
      "after": "b60f9069eab5193c",
      "attribution": {
        "page": "scratch"
      },
      "date": 1707798006126
    },
    {
      "item": {
        "type": "factory",
        "id": "61ecdc1aecc8e543"
      },
      "id": "61ecdc1aecc8e543",
      "type": "add",
      "after": "273643917e6cb71c",
      "date": 1707798011787
    },
    {
      "type": "edit",
      "id": "61ecdc1aecc8e543",
      "item": {
        "type": "frame",
        "id": "61ecdc1aecc8e543",
        "text": "//wiki.ralfbarkow.ch/assets/pages/story-telling/speed-bot.html\nHEIGHT 1500"
      },
      "date": 1707798014024
    },
    {
      "type": "add",
      "id": "906d1ef37edc37e4",
      "item": {
        "type": "paragraph",
        "id": "906d1ef37edc37e4",
        "text": "[[Kerry Turner]] "
      },
      "after": "b60f9069eab5193c",
      "date": 1707985209042
    },
    {
      "id": "010494efe8eeeee2",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "010494efe8eeeee2",
        "text": "[[Engagement vs Commitment]] (within [[ST2050]])"
      },
      "after": "906d1ef37edc37e4",
      "attribution": {
        "page": "E"
      },
      "date": 1707985227155
    },
    {
      "type": "remove",
      "id": "010494efe8eeeee2",
      "date": 1707985236738
    },
    {
      "type": "edit",
      "id": "906d1ef37edc37e4",
      "item": {
        "type": "paragraph",
        "id": "906d1ef37edc37e4",
        "text": "[[Kerry Turner]] See: [[Engagement vs Commitment]] (within [[ST2050]])"
      },
      "date": 1707985237892
    },
    {
      "type": "edit",
      "id": "61ecdc1aecc8e543",
      "item": {
        "type": "frame",
        "id": "61ecdc1aecc8e543",
        "text": "//wiki.ralfbarkow.ch/assets/pages/story-telling/speed-bot.html\nHEIGHT 250"
      },
      "date": 1708000748098
    },
    {
      "type": "add",
      "id": "97095af66bb334bd",
      "item": {
        "type": "paragraph",
        "id": "97095af66bb334bd",
        "text": "[[Kaiten Continuous Experience]]"
      },
      "after": "906d1ef37edc37e4",
      "date": 1708013873584
    },
    {
      "type": "edit",
      "id": "906d1ef37edc37e4",
      "item": {
        "type": "paragraph",
        "id": "906d1ef37edc37e4",
        "text": "**[[Kerry Turner]]** See: [[Engagement vs Commitment]] (within [[ST2050]])"
      },
      "date": 1708020583435
    },
    {
      "type": "add",
      "id": "b36d99dcb8c0341c",
      "item": {
        "type": "paragraph",
        "id": "b36d99dcb8c0341c",
        "text": "- [[Kerry's poetry]]"
      },
      "after": "906d1ef37edc37e4",
      "date": 1708020588292
    },
    {
      "type": "edit",
      "id": "906d1ef37edc37e4",
      "item": {
        "type": "markdown",
        "id": "906d1ef37edc37e4",
        "text": "**[[Kerry Turner]]** See: [[Engagement vs Commitment]] (within [[ST2050]])"
      },
      "date": 1708020592775
    },
    {
      "type": "add",
      "id": "05560528fb0944c6",
      "item": {
        "type": "paragraph",
        "id": "05560528fb0944c6",
        "text": "- [[Kerry Golden Paragraph]]"
      },
      "after": "b36d99dcb8c0341c",
      "date": 1709296838643
    },
    {
      "type": "edit",
      "id": "61ecdc1aecc8e543",
      "item": {
        "type": "frame",
        "id": "61ecdc1aecc8e543",
        "text": "//wiki.ralfbarkow.ch/assets/pages/speed-bot/speed-bot.html\nHEIGHT 222\nSOURCE graph\nSOURCE paragraph"
      },
      "date": 1713870390251
    },
    {
      "type": "add",
      "id": "a05bab4de90cb14c",
      "item": {
        "type": "paragraph",
        "id": "a05bab4de90cb14c",
        "text": "[[Körper]] See: [[Form des Körpers]]"
      },
      "after": "97095af66bb334bd",
      "date": 1719567134137
    },
    {
      "type": "edit",
      "id": "a05bab4de90cb14c",
      "item": {
        "type": "paragraph",
        "id": "a05bab4de90cb14c",
        "text": "[[Körper]] Siehe: [[Form des Körpers]]"
      },
      "date": 1719567150972
    }
  ]
}