{
  "title": "K",
  "story": [
    {
      "type": "pagefold",
      "id": "1dbcb05a56540609",
      "text": "List Indexcard K"
    },
    {
      "type": "paragraph",
      "id": "5533d22aad4e327d",
      "text": "[[Keyterm]] (within [[List Indexcards]])"
    },
    {
      "type": "paragraph",
      "id": "70e18e3045fac8ac",
      "text": "[[Knowledge]] (within [[Digital Garden]])"
    },
    {
      "type": "markdown",
      "id": "3ae6c4d835763bbe",
      "text": "- (within [[Narrative? Pattern!]])"
    },
    {
      "type": "paragraph",
      "id": "415e7900837d35ec",
      "text": "[[KWIC Index]] (within [[Typescript Locator]]) ⇒ [[Index]] "
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "K",
        "story": []
      },
      "date": 1706079142377
    },
    {
      "item": {
        "type": "factory",
        "id": "5533d22aad4e327d"
      },
      "id": "5533d22aad4e327d",
      "type": "add",
      "date": 1706079144200
    },
    {
      "type": "edit",
      "id": "5533d22aad4e327d",
      "item": {
        "type": "paragraph",
        "id": "5533d22aad4e327d",
        "text": "[[Keyterm] (within [[List Indexcards]])"
      },
      "date": 1706079160165
    },
    {
      "type": "edit",
      "id": "5533d22aad4e327d",
      "item": {
        "type": "paragraph",
        "id": "5533d22aad4e327d",
        "text": "[[Keyterm]] (within [[List Indexcards]])"
      },
      "date": 1706079165041
    },
    {
      "id": "1dbcb05a56540609",
      "type": "add",
      "item": {
        "type": "pagefold",
        "id": "1dbcb05a56540609",
        "text": "List Indexcard A"
      },
      "attribution": {
        "page": "A"
      },
      "date": 1706079169559
    },
    {
      "type": "edit",
      "id": "1dbcb05a56540609",
      "item": {
        "type": "pagefold",
        "id": "1dbcb05a56540609",
        "text": "List Indexcard K"
      },
      "date": 1706079174261
    },
    {
      "item": {
        "type": "factory",
        "id": "70e18e3045fac8ac"
      },
      "id": "70e18e3045fac8ac",
      "type": "add",
      "after": "5533d22aad4e327d",
      "date": 1706082042275
    },
    {
      "type": "edit",
      "id": "70e18e3045fac8ac",
      "item": {
        "type": "paragraph",
        "id": "70e18e3045fac8ac",
        "text": "[[Knowledge]] (within [[Digital Garden]])"
      },
      "date": 1706082054532
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1706084421972
    },
    {
      "type": "add",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "paragraph",
        "id": "3ae6c4d835763bbe",
        "text": "– (within [[Narrative? Pattern!]]"
      },
      "after": "70e18e3045fac8ac",
      "date": 1706084441906
    },
    {
      "type": "edit",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "paragraph",
        "id": "3ae6c4d835763bbe",
        "text": "- (within [[Narrative? Pattern!]]"
      },
      "date": 1706084454642
    },
    {
      "type": "edit",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "markdown",
        "id": "3ae6c4d835763bbe",
        "text": "- (within [[Narrative? Pattern!]]"
      },
      "date": 1706084456393
    },
    {
      "type": "edit",
      "id": "3ae6c4d835763bbe",
      "item": {
        "type": "markdown",
        "id": "3ae6c4d835763bbe",
        "text": "- (within [[Narrative? Pattern!]])"
      },
      "date": 1706084463657
    },
    {
      "item": {
        "type": "factory",
        "id": "415e7900837d35ec"
      },
      "id": "415e7900837d35ec",
      "type": "add",
      "after": "3ae6c4d835763bbe",
      "date": 1706103067928
    },
    {
      "type": "edit",
      "id": "415e7900837d35ec",
      "item": {
        "type": "paragraph",
        "id": "415e7900837d35ec",
        "text": "[[KWIC Index]] "
      },
      "date": 1706103070030
    },
    {
      "type": "edit",
      "id": "415e7900837d35ec",
      "item": {
        "type": "paragraph",
        "id": "415e7900837d35ec",
        "text": "[[KWIC Index]] (within [[Typescript Locator]])"
      },
      "date": 1706103098340
    },
    {
      "type": "edit",
      "id": "415e7900837d35ec",
      "item": {
        "type": "paragraph",
        "id": "415e7900837d35ec",
        "text": "[[KWIC Index]] (within [[Typescript Locator]]) ⇒ [[Index]] "
      },
      "date": 1706103127341
    }
  ]
}