{
  "title": "Leo",
  "story": [
    {
      "type": "paragraph",
      "id": "49e0cf5fb6efdfc7",
      "text": "Another system with snippet-level [[transclusion]] is [[Leo]] [https://leoeditor.com/ site], which uses it to good effect for code snippets (code reuse by transclusion). -- [[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]"
    },
    {
      "type": "markdown",
      "id": "bcba1a835b740806",
      "text": "> But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does `thisPage` refer to?"
    },
    {
      "type": "paragraph",
      "id": "1071fe52680d9dae",
      "text": "Leo’s underlying data is a [[Directed Acyclic Graph]]. [https://leoeditor.com/preface.html page]"
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "Leo",
        "story": []
      },
      "date": 1641231100876
    },
    {
      "id": "49e0cf5fb6efdfc7",
      "type": "add",
      "item": {
        "type": "paragraph",
        "id": "49e0cf5fb6efdfc7",
        "text": "[[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]\nAnother system with snippet-level transclusion is Leo (https://leoeditor.com/), which uses it to good effect for code snippets (code reuse by transclusion). But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does thisPage refer to?"
      },
      "date": 1641231141157
    },
    {
      "type": "edit",
      "id": "49e0cf5fb6efdfc7",
      "item": {
        "type": "paragraph",
        "id": "49e0cf5fb6efdfc7",
        "text": "[[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]\nAnother system with snippet-level transclusion is [[Leo]] [https://leoeditor.com/ site], which uses it to good effect for code snippets (code reuse by transclusion). But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does thisPage refer to?"
      },
      "date": 1641231184832
    },
    {
      "item": {
        "type": "factory",
        "id": "1071fe52680d9dae"
      },
      "id": "1071fe52680d9dae",
      "type": "add",
      "after": "49e0cf5fb6efdfc7",
      "date": 1641231339106
    },
    {
      "type": "edit",
      "id": "1071fe52680d9dae",
      "item": {
        "type": "paragraph",
        "id": "1071fe52680d9dae",
        "text": "Leo’s underlying data is a Directed Acyclic Graphs. "
      },
      "date": 1641231341652
    },
    {
      "type": "edit",
      "id": "1071fe52680d9dae",
      "item": {
        "type": "paragraph",
        "id": "1071fe52680d9dae",
        "text": "Leo’s underlying data is a Directed Acyclic Graphs. [https://leoeditor.com/preface.html page]"
      },
      "date": 1641231349883
    },
    {
      "type": "edit",
      "id": "49e0cf5fb6efdfc7",
      "item": {
        "type": "paragraph",
        "id": "49e0cf5fb6efdfc7",
        "text": "[[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]\nAnother system with snippet-level transclusion is [[Leo]] [https://leoeditor.com/ site], which uses it to good effect for code snippets (code reuse by transclusion). "
      },
      "date": 1641231428900
    },
    {
      "type": "add",
      "id": "bcba1a835b740806",
      "item": {
        "type": "paragraph",
        "id": "bcba1a835b740806",
        "text": "But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does thisPage refer to?"
      },
      "after": "49e0cf5fb6efdfc7",
      "date": 1641231431309
    },
    {
      "type": "edit",
      "id": "49e0cf5fb6efdfc7",
      "item": {
        "type": "paragraph",
        "id": "49e0cf5fb6efdfc7",
        "text": "\nAnother system with snippet-level transclusion is [[Leo]] [https://leoeditor.com/ site], which uses it to good effect for code snippets (code reuse by transclusion). -- [[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]"
      },
      "date": 1641231437416
    },
    {
      "type": "edit",
      "id": "49e0cf5fb6efdfc7",
      "item": {
        "type": "paragraph",
        "id": "49e0cf5fb6efdfc7",
        "text": "Another system with snippet-level transclusion is [[Leo]] [https://leoeditor.com/ site], which uses it to good effect for code snippets (code reuse by transclusion). -- [[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]"
      },
      "date": 1641231440548
    },
    {
      "type": "edit",
      "id": "bcba1a835b740806",
      "item": {
        "type": "paragraph",
        "id": "bcba1a835b740806",
        "text": "But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does `thisPage` refer to?"
      },
      "date": 1641231474236
    },
    {
      "type": "edit",
      "id": "bcba1a835b740806",
      "item": {
        "type": "markdown",
        "id": "bcba1a835b740806",
        "text": "But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does `thisPage` refer to?"
      },
      "date": 1641231476228
    },
    {
      "type": "edit",
      "id": "bcba1a835b740806",
      "item": {
        "type": "markdown",
        "id": "bcba1a835b740806",
        "text": "> But that also raises new challenges: if a Pharo snippet can live in multiple pages, what does `thisPage` refer to?"
      },
      "date": 1641231500970
    },
    {
      "type": "edit",
      "id": "1071fe52680d9dae",
      "item": {
        "type": "paragraph",
        "id": "1071fe52680d9dae",
        "text": "Leo’s underlying data is a [[Directed Acyclic Graph]]. [https://leoeditor.com/preface.html page]"
      },
      "date": 1641231546102
    },
    {
      "type": "edit",
      "id": "49e0cf5fb6efdfc7",
      "item": {
        "type": "paragraph",
        "id": "49e0cf5fb6efdfc7",
        "text": "Another system with snippet-level [[transclusion]] is [[Leo]] [https://leoeditor.com/ site], which uses it to good effect for code snippets (code reuse by transclusion). -- [[Konrad Hinsen]] via [https://discord.com/channels/729445214812504107/729445215341117522/927571939713757224 discord]"
      },
      "date": 1641231561032
    }
  ]
}