{
  "title": "ma",
  "story": [
    {
      "type": "markdown",
      "id": "50fc05ed81a0a470",
      "text": "“The big idea is **[[Messaging]]** — that is what the kernel of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
    },
    {
      "type": "pagefold",
      "id": "c0664eeabe8356d3",
      "text": "~"
    },
    {
      "type": "reference",
      "id": "e2bdda6d0fade784",
      "site": "splash.fed.wiki.org",
      "slug": "messaging",
      "title": "Messaging",
      "text": "Communication and collaboration is based upon exchange of [[Polymorphic]] messages rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
    },
    {
      "type": "reference",
      "id": "5e945643184c13f5",
      "site": "thompson.forage.ustawi.wiki",
      "slug": "the-space-between",
      "title": "The Space Between",
      "text": "Phil Jackson, the renown basketball coach – Michael Jordon's coach – would tell his players on the court to always look for the space between."
    },
    {
      "type": "graphviz",
      "id": "dbdc2635b2664ce7",
      "text": "DOT FROM two-level-diagram",
      "dot": "strict digraph {rankdir=LR\nnode [shape=plaintext]\n\"ma\" -> \"interstitial\"\n\"ma\" -> \"Alan\nKay\"\n\"ma\" -> \"Polymorphic\"\n\"interstitial\" -> \"ma\"\n\"Alan\nKay\" -> \"Seymour\nPapert\"\n\"Alan\nKay\" -> \"Blue\nPlane\"\n\"Alan\nKay\" -> \"Smalltalk\"\n\"Polymorphic\" -> \"We\"\n\"Polymorphic\" -> \"fetch\"\n\"Polymorphic\" -> \"History\"\n\"Polymorphic\" -> \"Memory\"\n\"Polymorphic\" -> \"Journal\"\n\"Polymorphic\" -> \"Polymorphism\"\n\"Polymorphic\" -> \"Structure\"\n\"Polymorphic\" -> \"polymorphic\"\n\"Polymorphic\" -> \"Juan\nVuletich\"}",
      "svg": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 8.0.5 (0)\n -->\n<!-- Pages: 1 -->\n<svg width=\"321pt\" height=\"656pt\"\n viewBox=\"0.00 0.00 320.79 655.60\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 651.6)\">\n<polygon fill=\"white\" stroke=\"none\" points=\"-4,4 -4,-651.6 316.79,-651.6 316.79,4 -4,4\"/>\n<!-- ma -->\n<g id=\"node1\" class=\"node\">\n<title>ma</title>\n<text text-anchor=\"middle\" x=\"27\" y=\"-561.6\" font-family=\"Times,serif\" font-size=\"14.00\">ma</text>\n</g>\n<!-- interstitial -->\n<g id=\"node2\" class=\"node\">\n<title>interstitial</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-590.6\" font-family=\"Times,serif\" font-size=\"14.00\">interstitial</text>\n</g>\n<!-- ma&#45;&gt;interstitial -->\n<g id=\"edge1\" class=\"edge\">\n<title>ma&#45;&gt;interstitial</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54,-567.05C64.15,-569.16 76.09,-572.19 87.59,-575.53\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"86.36,-579.12 96.95,-578.68 88.39,-572.43 86.36,-579.12\"/>\n</g>\n<!-- Alan\nKay -->\n<g id=\"node3\" class=\"node\">\n<title>Alan\nKay</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-542\" font-family=\"Times,serif\" font-size=\"14.00\">Alan</text>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-525.2\" font-family=\"Times,serif\" font-size=\"14.00\">Kay</text>\n</g>\n<!-- ma&#45;&gt;Alan\nKay -->\n<g id=\"edge2\" class=\"edge\">\n<title>ma&#45;&gt;Alan\nKay</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54,-558.88C66.99,-555.42 82.91,-551.18 97.07,-547.41\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"97.71,-550.6 106.47,-544.64 95.9,-543.83 97.71,-550.6\"/>\n</g>\n<!-- Polymorphic -->\n<g id=\"node4\" class=\"node\">\n<title>Polymorphic</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-262.6\" font-family=\"Times,serif\" font-size=\"14.00\">Polymorphic</text>\n</g>\n<!-- ma&#45;&gt;Polymorphic -->\n<g id=\"edge3\" class=\"edge\">\n<title>ma&#45;&gt;Polymorphic</title>\n<path fill=\"none\" stroke=\"black\" d=\"M34.26,-547.99C51.87,-497.93 101.92,-355.64 123.29,-294.87\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"126.92,-296.11 126.93,-285.52 120.31,-293.79 126.92,-296.11\"/>\n</g>\n<!-- interstitial&#45;&gt;ma -->\n<g id=\"edge4\" class=\"edge\">\n<title>interstitial&#45;&gt;ma</title>\n<path fill=\"none\" stroke=\"black\" d=\"M97.95,-591.5C87.17,-588.96 75.29,-585.7 64.44,-582.31\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"65.59,-578.67 55,-578.88 63.41,-585.32 65.59,-578.67\"/>\n</g>\n<!-- Seymour\nPapert -->\n<g id=\"node5\" class=\"node\">\n<title>Seymour\nPapert</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-631\" font-family=\"Times,serif\" font-size=\"14.00\">Seymour</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-614.2\" font-family=\"Times,serif\" font-size=\"14.00\">Papert</text>\n</g>\n<!-- Alan\nKay&#45;&gt;Seymour\nPapert -->\n<g id=\"edge5\" class=\"edge\">\n<title>Alan\nKay&#45;&gt;Seymour\nPapert</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.94,-555.27C166.72,-559.31 172.78,-563.64 178.33,-567.8 194.78,-580.11 197.58,-584.91 214.33,-596.8 216.55,-598.37 218.85,-599.96 221.18,-601.53\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"219.01,-604.94 229.29,-607.49 222.84,-599.08 219.01,-604.94\"/>\n</g>\n<!-- Blue\nPlane -->\n<g id=\"node6\" class=\"node\">\n<title>Blue\nPlane</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-571\" font-family=\"Times,serif\" font-size=\"14.00\">Blue</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-554.2\" font-family=\"Times,serif\" font-size=\"14.00\">Plane</text>\n</g>\n<!-- Alan\nKay&#45;&gt;Blue\nPlane -->\n<g id=\"edge6\" class=\"edge\">\n<title>Alan\nKay&#45;&gt;Blue\nPlane</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.95,-543.67C179.68,-547.93 205.3,-553.76 226.12,-558.51\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.29,-562.13 235.82,-560.94 226.84,-555.31 225.29,-562.13\"/>\n</g>\n<!-- Smalltalk -->\n<g id=\"node7\" class=\"node\">\n<title>Smalltalk</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-505.6\" font-family=\"Times,serif\" font-size=\"14.00\">Smalltalk</text>\n</g>\n<!-- Alan\nKay&#45;&gt;Smalltalk -->\n<g id=\"edge7\" class=\"edge\">\n<title>Alan\nKay&#45;&gt;Smalltalk</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.95,-532.13C177.43,-528.51 199.25,-523.72 218.44,-519.5\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"219.06,-522.73 228.07,-517.16 217.55,-515.89 219.06,-522.73\"/>\n</g>\n<!-- We -->\n<g id=\"node8\" class=\"node\">\n<title>We</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-451.6\" font-family=\"Times,serif\" font-size=\"14.00\">We</text>\n</g>\n<!-- Polymorphic&#45;&gt;We -->\n<g id=\"edge8\" class=\"edge\">\n<title>Polymorphic&#45;&gt;We</title>\n<path fill=\"none\" stroke=\"black\" d=\"M140.01,-284.68C149.53,-316.92 173.36,-385.47 214.33,-428.8 218.15,-432.84 222.7,-436.43 227.47,-439.57\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.37,-442.98 235.76,-445.05 228.93,-436.95 225.37,-442.98\"/>\n</g>\n<!-- fetch -->\n<g id=\"node9\" class=\"node\">\n<title>fetch</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-397.6\" font-family=\"Times,serif\" font-size=\"14.00\">fetch</text>\n</g>\n<!-- Polymorphic&#45;&gt;fetch -->\n<g id=\"edge9\" class=\"edge\">\n<title>Polymorphic&#45;&gt;fetch</title>\n<path fill=\"none\" stroke=\"black\" d=\"M145,-284.69C158.35,-307.74 184.03,-348 214.33,-374.8 218.26,-378.27 222.7,-381.49 227.27,-384.41\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.29,-387.9 235.68,-389.96 228.84,-381.86 225.29,-387.9\"/>\n</g>\n<!-- History -->\n<g id=\"node10\" class=\"node\">\n<title>History</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-343.6\" font-family=\"Times,serif\" font-size=\"14.00\">History</text>\n</g>\n<!-- Polymorphic&#45;&gt;History -->\n<g id=\"edge10\" class=\"edge\">\n<title>Polymorphic&#45;&gt;History</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.1,-284.64C175.51,-295.45 195.8,-309.32 214.33,-320.8 217.9,-323.01 221.66,-325.25 225.44,-327.45\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"223.35,-330.87 233.77,-332.79 226.83,-324.79 223.35,-330.87\"/>\n</g>\n<!-- Memory -->\n<g id=\"node11\" class=\"node\">\n<title>Memory</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-289.6\" font-family=\"Times,serif\" font-size=\"14.00\">Memory</text>\n</g>\n<!-- Polymorphic&#45;&gt;Memory -->\n<g id=\"edge11\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Memory</title>\n<path fill=\"none\" stroke=\"black\" d=\"M178.3,-275.94C192.08,-278.86 207.3,-282.09 220.97,-284.99\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"220.04,-288.58 230.55,-287.23 221.49,-281.73 220.04,-288.58\"/>\n</g>\n<!-- Journal -->\n<g id=\"node12\" class=\"node\">\n<title>Journal</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-235.6\" font-family=\"Times,serif\" font-size=\"14.00\">Journal</text>\n</g>\n<!-- Polymorphic&#45;&gt;Journal -->\n<g id=\"edge12\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Journal</title>\n<path fill=\"none\" stroke=\"black\" d=\"M178.3,-257.66C193.25,-254.49 209.9,-250.96 224.42,-247.88\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225,-251.13 234.05,-245.63 223.55,-244.28 225,-251.13\"/>\n</g>\n<!-- Polymorphism -->\n<g id=\"node13\" class=\"node\">\n<title>Polymorphism</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-181.6\" font-family=\"Times,serif\" font-size=\"14.00\">Polymorphism</text>\n</g>\n<!-- Polymorphic&#45;&gt;Polymorphism -->\n<g id=\"edge13\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Polymorphism</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.1,-248.96C175.51,-238.15 195.8,-224.28 214.33,-212.8 216.32,-211.57 218.37,-210.33 220.44,-209.09\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"221.77,-211.78 228.64,-203.71 218.24,-205.73 221.77,-211.78\"/>\n</g>\n<!-- Structure -->\n<g id=\"node14\" class=\"node\">\n<title>Structure</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-127.6\" font-family=\"Times,serif\" font-size=\"14.00\">Structure</text>\n</g>\n<!-- Polymorphic&#45;&gt;Structure -->\n<g id=\"edge14\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Structure</title>\n<path fill=\"none\" stroke=\"black\" d=\"M145,-248.91C158.35,-225.86 184.03,-185.6 214.33,-158.8 216.55,-156.83 218.94,-154.95 221.43,-153.15\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"222.71,-155.84 229.13,-147.41 218.86,-149.99 222.71,-155.84\"/>\n</g>\n<!-- polymorphic -->\n<g id=\"node15\" class=\"node\">\n<title>polymorphic</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-73.6\" font-family=\"Times,serif\" font-size=\"14.00\">polymorphic</text>\n</g>\n<!-- Polymorphic&#45;&gt;polymorphic -->\n<g id=\"edge15\" class=\"edge\">\n<title>Polymorphic&#45;&gt;polymorphic</title>\n<path fill=\"none\" stroke=\"black\" d=\"M140.01,-248.92C149.53,-216.68 173.36,-148.13 214.33,-104.8 215.12,-103.96 215.95,-103.15 216.8,-102.35\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"218.47,-104.69 224.05,-95.68 214.07,-99.24 218.47,-104.69\"/>\n</g>\n<!-- Juan\nVuletich -->\n<g id=\"node16\" class=\"node\">\n<title>Juan\nVuletich</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-25\" font-family=\"Times,serif\" font-size=\"14.00\">Juan</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-8.2\" font-family=\"Times,serif\" font-size=\"14.00\">Vuletich</text>\n</g>\n<!-- Polymorphic&#45;&gt;Juan\nVuletich -->\n<g id=\"edge16\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Juan\nVuletich</title>\n<path fill=\"none\" stroke=\"black\" d=\"M137.69,-248.91C144.06,-209.26 164.06,-112.62 214.33,-50.8 216.84,-47.71 219.76,-44.85 222.9,-42.22\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"224.61,-44.57 230.57,-35.81 220.45,-38.94 224.61,-44.57\"/>\n</g>\n</g>\n</svg>\n"
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "ma",
        "story": []
      },
      "date": 1660287096845
    },
    {
      "item": {
        "type": "factory",
        "id": "50fc05ed81a0a470"
      },
      "id": "50fc05ed81a0a470",
      "type": "add",
      "date": 1660287101583
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is messaging — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word [[ma]] — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —Alan Kay"
      },
      "date": 1660287109618
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is messaging — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1660287128848
    },
    {
      "item": {
        "type": "factory",
        "id": "c0664eeabe8356d3"
      },
      "id": "c0664eeabe8356d3",
      "type": "add",
      "after": "50fc05ed81a0a470",
      "date": 1702404111491
    },
    {
      "type": "edit",
      "id": "c0664eeabe8356d3",
      "item": {
        "type": "pagefold",
        "id": "c0664eeabe8356d3",
        "text": "~"
      },
      "date": 1702404114515
    },
    {
      "item": {
        "type": "factory",
        "id": "5e945643184c13f5"
      },
      "id": "5e945643184c13f5",
      "type": "add",
      "after": "c0664eeabe8356d3",
      "date": 1702404115882
    },
    {
      "type": "edit",
      "id": "5e945643184c13f5",
      "item": {
        "type": "reference",
        "id": "5e945643184c13f5",
        "site": "thompson.forage.ustawi.wiki",
        "slug": "the-space-between",
        "title": "The Space Between",
        "text": "Phil Jackson, the renown basketball coach – Michael Jordon's coach – would tell his players on the court to always look for the space between."
      },
      "date": 1702404123980
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is [[Messaging]] — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702404340867
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1702404360844
    },
    {
      "item": {
        "type": "factory",
        "id": "e2bdda6d0fade784"
      },
      "id": "e2bdda6d0fade784",
      "type": "add",
      "after": "5e945643184c13f5",
      "date": 1702404530672
    },
    {
      "type": "edit",
      "id": "e2bdda6d0fade784",
      "item": {
        "type": "reference",
        "id": "e2bdda6d0fade784",
        "site": "splash.fed.wiki.org",
        "slug": "messaging",
        "title": "Messaging",
        "text": "Communication and collaboration is based upon exchange of polymorphic messages rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
      },
      "date": 1702404535030
    },
    {
      "id": "e2bdda6d0fade784",
      "type": "move",
      "order": [
        "50fc05ed81a0a470",
        "c0664eeabe8356d3",
        "e2bdda6d0fade784",
        "5e945643184c13f5"
      ],
      "date": 1702404539816
    },
    {
      "type": "edit",
      "id": "e2bdda6d0fade784",
      "item": {
        "type": "reference",
        "id": "e2bdda6d0fade784",
        "site": "splash.fed.wiki.org",
        "slug": "messaging",
        "title": "Messaging",
        "text": "Communication and collaboration is based upon exchange of [[Polymorphic]] [[Messages]] rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
      },
      "date": 1702404889034
    },
    {
      "item": {
        "type": "factory",
        "id": "dbdc2635b2664ce7"
      },
      "id": "dbdc2635b2664ce7",
      "type": "add",
      "after": "5e945643184c13f5",
      "date": 1702404902282
    },
    {
      "type": "edit",
      "id": "dbdc2635b2664ce7",
      "item": {
        "type": "graphviz",
        "id": "dbdc2635b2664ce7",
        "text": "DOT FROM two-level-diagrams"
      },
      "date": 1702404914462
    },
    {
      "type": "edit",
      "id": "dbdc2635b2664ce7",
      "item": {
        "type": "graphviz",
        "id": "dbdc2635b2664ce7",
        "text": "DOT FROM two-level-diagram"
      },
      "date": 1702404932163
    },
    {
      "type": "fork",
      "site": "wiki.ralfbarkow.ch",
      "date": 1702405093183
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is Messaging — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702405949990
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **messaging** — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702405986212
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "markdown",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **messaging** — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702405989478
    },
    {
      "type": "edit",
      "id": "e2bdda6d0fade784",
      "item": {
        "type": "reference",
        "id": "e2bdda6d0fade784",
        "site": "splash.fed.wiki.org",
        "slug": "messaging",
        "title": "Messaging",
        "text": "Communication and collaboration is based upon exchange of [[Polymorphic]] messages rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
      },
      "date": 1702406013526
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "markdown",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **messaging** — that is what the kernel of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702406204026
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1702406302876
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "markdown",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **[[Messaging]]** — that is what the kernel of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1707116282976
    }
  ]
}