{
  "title": "ma",
  "story": [
    {
      "type": "markdown",
      "id": "50fc05ed81a0a470",
      "text": "“The big idea is **[[Messaging]]** — that is what the kernel of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
    },
    {
      "type": "pagefold",
      "id": "c0664eeabe8356d3",
      "text": "~"
    },
    {
      "type": "reference",
      "id": "e2bdda6d0fade784",
      "site": "splash.fed.wiki.org",
      "slug": "messaging",
      "title": "Messaging",
      "text": "Communication and collaboration is based upon exchange of [[Polymorphic]] messages rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
    },
    {
      "type": "reference",
      "id": "5e945643184c13f5",
      "site": "thompson.forage.ustawi.wiki",
      "slug": "the-space-between",
      "title": "The Space Between",
      "text": "Phil Jackson, the renown basketball coach – Michael Jordon's coach – would tell his players on the court to always look for the space between."
    },
    {
      "type": "graphviz",
      "id": "dbdc2635b2664ce7",
      "text": "DOT FROM two-level-diagram",
      "dot": "strict digraph {rankdir=LR\nnode [shape=plaintext]\n\"ma\" -> \"Messaging\"\n\"ma\" -> \"interstitial\"\n\"ma\" -> \"Alan\nKay\"\n\"ma\" -> \"Polymorphic\"\n\"Messaging\" -> \"Steve\nBurbeck\"\n\"Messaging\" -> \"Frame\"\n\"Messaging\" -> \"Frame\nPlugin\"\n\"Messaging\" -> \"Interop’s\nLabyrinth\"\n\"Messaging\" -> \"API\"\n\"Messaging\" -> \"WHATWG\"\n\"Messaging\" -> \"HTML5\"\n\"Messaging\" -> \"IFrame\"\n\"interstitial\" -> \"ma\"\n\"Alan\nKay\" -> \"Seymour\nPapert\"\n\"Alan\nKay\" -> \"Blue\nPlane\"\n\"Alan\nKay\" -> \"Smalltalk\"\n\"Polymorphic\" -> \"fetch\"\n\"Polymorphic\" -> \"History\"\n\"Polymorphic\" -> \"Memory\"\n\"Polymorphic\" -> \"Journal\"\n\"Polymorphic\" -> \"Polymorphism\"\n\"Polymorphic\" -> \"Structure\"}",
      "svg": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 8.0.5 (0)\n -->\n<!-- Pages: 1 -->\n<svg width=\"321pt\" height=\"938pt\"\n viewBox=\"0.00 0.00 320.79 937.80\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 933.8)\">\n<polygon fill=\"white\" stroke=\"none\" points=\"-4,4 -4,-933.8 316.79,-933.8 316.79,4 -4,4\"/>\n<!-- ma -->\n<g id=\"node1\" class=\"node\">\n<title>ma</title>\n<text text-anchor=\"middle\" x=\"27\" y=\"-451.8\" font-family=\"Times,serif\" font-size=\"14.00\">ma</text>\n</g>\n<!-- Messaging -->\n<g id=\"node2\" class=\"node\">\n<title>Messaging</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-673.8\" font-family=\"Times,serif\" font-size=\"14.00\">Messaging</text>\n</g>\n<!-- ma&#45;&gt;Messaging -->\n<g id=\"edge1\" class=\"edge\">\n<title>ma&#45;&gt;Messaging</title>\n<path fill=\"none\" stroke=\"black\" d=\"M36.43,-473.79C54.74,-512.44 98.24,-604.28 120.12,-650.47\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"117.25,-651.58 124.7,-659.12 123.58,-648.59 117.25,-651.58\"/>\n</g>\n<!-- interstitial -->\n<g id=\"node3\" class=\"node\">\n<title>interstitial</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-451.8\" font-family=\"Times,serif\" font-size=\"14.00\">interstitial</text>\n</g>\n<!-- ma&#45;&gt;interstitial -->\n<g id=\"edge2\" class=\"edge\">\n<title>ma&#45;&gt;interstitial</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54,-450.08C64.04,-449.39 75.85,-449.13 87.23,-449.3\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"86.86,-452.82 96.95,-449.59 87.05,-445.82 86.86,-452.82\"/>\n</g>\n<!-- Alan\nKay -->\n<g id=\"node4\" class=\"node\">\n<title>Alan\nKay</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-403.2\" font-family=\"Times,serif\" font-size=\"14.00\">Alan</text>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-386.4\" font-family=\"Times,serif\" font-size=\"14.00\">Kay</text>\n</g>\n<!-- ma&#45;&gt;Alan\nKay -->\n<g id=\"edge3\" class=\"edge\">\n<title>ma&#45;&gt;Alan\nKay</title>\n<path fill=\"none\" stroke=\"black\" d=\"M54,-441.91C67.24,-434.73 83.54,-425.9 97.9,-418.11\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"99.34,-420.77 106.47,-412.93 96.01,-414.62 99.34,-420.77\"/>\n</g>\n<!-- Polymorphic -->\n<g id=\"node5\" class=\"node\">\n<title>Polymorphic</title>\n<text text-anchor=\"middle\" x=\"134.17\" y=\"-175.8\" font-family=\"Times,serif\" font-size=\"14.00\">Polymorphic</text>\n</g>\n<!-- ma&#45;&gt;Polymorphic -->\n<g id=\"edge4\" class=\"edge\">\n<title>ma&#45;&gt;Polymorphic</title>\n<path fill=\"none\" stroke=\"black\" d=\"M34.74,-438.32C52.54,-391.59 100.94,-264.59 122.52,-207.93\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"126.06,-209.49 126.35,-198.89 119.52,-206.99 126.06,-209.49\"/>\n</g>\n<!-- Steve\nBurbeck -->\n<g id=\"node6\" class=\"node\">\n<title>Steve\nBurbeck</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-913.2\" font-family=\"Times,serif\" font-size=\"14.00\">Steve</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-896.4\" font-family=\"Times,serif\" font-size=\"14.00\">Burbeck</text>\n</g>\n<!-- Messaging&#45;&gt;Steve\nBurbeck -->\n<g id=\"edge5\" class=\"edge\">\n<title>Messaging&#45;&gt;Steve\nBurbeck</title>\n<path fill=\"none\" stroke=\"black\" d=\"M138.25,-695.78C145.54,-733.36 166.91,-822.1 214.33,-879 216.91,-882.1 219.9,-884.97 223.1,-887.62\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"220.79,-890.99 230.93,-894.06 224.92,-885.34 220.79,-890.99\"/>\n</g>\n<!-- Frame -->\n<g id=\"node7\" class=\"node\">\n<title>Frame</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-847.8\" font-family=\"Times,serif\" font-size=\"14.00\">Frame</text>\n</g>\n<!-- Messaging&#45;&gt;Frame -->\n<g id=\"edge6\" class=\"edge\">\n<title>Messaging&#45;&gt;Frame</title>\n<path fill=\"none\" stroke=\"black\" d=\"M141.03,-695.86C151.6,-725.73 176.32,-786.36 214.33,-825 218.19,-828.92 222.73,-832.43 227.46,-835.53\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.27,-838.9 235.66,-840.97 228.84,-832.87 225.27,-838.9\"/>\n</g>\n<!-- Frame\nPlugin -->\n<g id=\"node8\" class=\"node\">\n<title>Frame\nPlugin</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-799.2\" font-family=\"Times,serif\" font-size=\"14.00\">Frame</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-782.4\" font-family=\"Times,serif\" font-size=\"14.00\">Plugin</text>\n</g>\n<!-- Messaging&#45;&gt;Frame\nPlugin -->\n<g id=\"edge7\" class=\"edge\">\n<title>Messaging&#45;&gt;Frame\nPlugin</title>\n<path fill=\"none\" stroke=\"black\" d=\"M148.79,-695.67C163.65,-714.25 188.75,-743.7 214.33,-765 218.49,-768.46 223.07,-771.82 227.72,-774.95\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.32,-778.21 235.62,-780.68 229.11,-772.33 225.32,-778.21\"/>\n</g>\n<!-- Interop’s\nLabyrinth -->\n<g id=\"node9\" class=\"node\">\n<title>Interop’s\nLabyrinth</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-739.2\" font-family=\"Times,serif\" font-size=\"14.00\">Interop’s</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-722.4\" font-family=\"Times,serif\" font-size=\"14.00\">Labyrinth</text>\n</g>\n<!-- Messaging&#45;&gt;Interop’s\nLabyrinth -->\n<g id=\"edge8\" class=\"edge\">\n<title>Messaging&#45;&gt;Interop’s\nLabyrinth</title>\n<path fill=\"none\" stroke=\"black\" d=\"M172.36,-694.64C186.56,-700.99 202.9,-708.31 217.74,-714.95\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"216.17,-718.53 226.73,-719.41 219.03,-712.14 216.17,-718.53\"/>\n</g>\n<!-- API -->\n<g id=\"node10\" class=\"node\">\n<title>API</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-673.8\" font-family=\"Times,serif\" font-size=\"14.00\">API</text>\n</g>\n<!-- Messaging&#45;&gt;API -->\n<g id=\"edge9\" class=\"edge\">\n<title>Messaging&#45;&gt;API</title>\n<path fill=\"none\" stroke=\"black\" d=\"M172.36,-678C189.34,-678 209.4,-678 226.27,-678\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.84,-681.5 235.84,-678 225.84,-674.5 225.84,-681.5\"/>\n</g>\n<!-- WHATWG -->\n<g id=\"node11\" class=\"node\">\n<title>WHATWG</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-619.8\" font-family=\"Times,serif\" font-size=\"14.00\">WHATWG</text>\n</g>\n<!-- Messaging&#45;&gt;WHATWG -->\n<g id=\"edge10\" class=\"edge\">\n<title>Messaging&#45;&gt;WHATWG</title>\n<path fill=\"none\" stroke=\"black\" d=\"M172.36,-662.24C185.24,-656.77 199.88,-650.57 213.57,-644.77\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"214.48,-647.76 222.33,-640.63 211.75,-641.31 214.48,-647.76\"/>\n</g>\n<!-- HTML5 -->\n<g id=\"node12\" class=\"node\">\n<title>HTML5</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-565.8\" font-family=\"Times,serif\" font-size=\"14.00\">HTML5</text>\n</g>\n<!-- Messaging&#45;&gt;HTML5 -->\n<g id=\"edge11\" class=\"edge\">\n<title>Messaging&#45;&gt;HTML5</title>\n<path fill=\"none\" stroke=\"black\" d=\"M149.96,-660.11C164.98,-642.65 189.51,-616.01 214.33,-597 217.11,-594.87 220.08,-592.8 223.13,-590.81\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"224.69,-593.35 231.38,-585.14 221.03,-587.38 224.69,-593.35\"/>\n</g>\n<!-- IFrame -->\n<g id=\"node13\" class=\"node\">\n<title>IFrame</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-511.8\" font-family=\"Times,serif\" font-size=\"14.00\">IFrame</text>\n</g>\n<!-- Messaging&#45;&gt;IFrame -->\n<g id=\"edge12\" class=\"edge\">\n<title>Messaging&#45;&gt;IFrame</title>\n<path fill=\"none\" stroke=\"black\" d=\"M141.96,-660.28C153.35,-632.43 178.63,-578 214.33,-543 217.86,-539.54 221.91,-536.39 226.15,-533.55\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"227.81,-536.02 234.55,-527.85 224.19,-530.04 227.81,-536.02\"/>\n</g>\n<!-- interstitial&#45;&gt;ma -->\n<g id=\"edge13\" class=\"edge\">\n<title>interstitial&#45;&gt;ma</title>\n<path fill=\"none\" stroke=\"black\" d=\"M97.95,-462.41C87.28,-462.84 75.54,-462.86 64.78,-462.47\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"65.16,-458.94 55,-461.92 64.8,-465.93 65.16,-458.94\"/>\n</g>\n<!-- Seymour\nPapert -->\n<g id=\"node14\" class=\"node\">\n<title>Seymour\nPapert</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-463.2\" font-family=\"Times,serif\" font-size=\"14.00\">Seymour</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-446.4\" font-family=\"Times,serif\" font-size=\"14.00\">Papert</text>\n</g>\n<!-- Alan\nKay&#45;&gt;Seymour\nPapert -->\n<g id=\"edge14\" class=\"edge\">\n<title>Alan\nKay&#45;&gt;Seymour\nPapert</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.95,-411.14C178.11,-419.23 201.05,-430.03 220.8,-439.33\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"218.95,-442.8 229.48,-443.89 221.93,-436.47 218.95,-442.8\"/>\n</g>\n<!-- Blue\nPlane -->\n<g id=\"node15\" class=\"node\">\n<title>Blue\nPlane</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-403.2\" font-family=\"Times,serif\" font-size=\"14.00\">Blue</text>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-386.4\" font-family=\"Times,serif\" font-size=\"14.00\">Plane</text>\n</g>\n<!-- Alan\nKay&#45;&gt;Blue\nPlane -->\n<g id=\"edge15\" class=\"edge\">\n<title>Alan\nKay&#45;&gt;Blue\nPlane</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.95,-399C179.59,-399 205.06,-399 225.83,-399\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.82,-402.5 235.82,-399 225.82,-395.5 225.82,-402.5\"/>\n</g>\n<!-- Smalltalk -->\n<g id=\"node16\" class=\"node\">\n<title>Smalltalk</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-337.8\" font-family=\"Times,serif\" font-size=\"14.00\">Smalltalk</text>\n</g>\n<!-- Alan\nKay&#45;&gt;Smalltalk -->\n<g id=\"edge16\" class=\"edge\">\n<title>Alan\nKay&#45;&gt;Smalltalk</title>\n<path fill=\"none\" stroke=\"black\" d=\"M160.95,-387.47C177.66,-379.99 199.86,-370.06 219.24,-361.38\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"220.37,-364.26 228.07,-356.98 217.51,-357.87 220.37,-364.26\"/>\n</g>\n<!-- fetch -->\n<g id=\"node17\" class=\"node\">\n<title>fetch</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-283.8\" font-family=\"Times,serif\" font-size=\"14.00\">fetch</text>\n</g>\n<!-- Polymorphic&#45;&gt;fetch -->\n<g id=\"edge17\" class=\"edge\">\n<title>Polymorphic&#45;&gt;fetch</title>\n<path fill=\"none\" stroke=\"black\" d=\"M149.96,-197.89C164.98,-215.35 189.51,-241.99 214.33,-261 218.4,-264.12 222.87,-267.11 227.4,-269.89\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"225.27,-273.28 235.67,-275.29 228.79,-267.23 225.27,-273.28\"/>\n</g>\n<!-- History -->\n<g id=\"node18\" class=\"node\">\n<title>History</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-229.8\" font-family=\"Times,serif\" font-size=\"14.00\">History</text>\n</g>\n<!-- Polymorphic&#45;&gt;History -->\n<g id=\"edge18\" class=\"edge\">\n<title>Polymorphic&#45;&gt;History</title>\n<path fill=\"none\" stroke=\"black\" d=\"M177.59,-197.98C192.88,-204.46 210.01,-211.73 224.87,-218.03\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"223.17,-221.53 233.74,-222.21 225.9,-215.08 223.17,-221.53\"/>\n</g>\n<!-- Memory -->\n<g id=\"node19\" class=\"node\">\n<title>Memory</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-175.8\" font-family=\"Times,serif\" font-size=\"14.00\">Memory</text>\n</g>\n<!-- Polymorphic&#45;&gt;Memory -->\n<g id=\"edge19\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Memory</title>\n<path fill=\"none\" stroke=\"black\" d=\"M178.3,-180C191.94,-180 207,-180 220.57,-180\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"220.55,-183.5 230.55,-180 220.55,-176.5 220.55,-183.5\"/>\n</g>\n<!-- Journal -->\n<g id=\"node20\" class=\"node\">\n<title>Journal</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-121.8\" font-family=\"Times,serif\" font-size=\"14.00\">Journal</text>\n</g>\n<!-- Polymorphic&#45;&gt;Journal -->\n<g id=\"edge20\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Journal</title>\n<path fill=\"none\" stroke=\"black\" d=\"M177.59,-162.02C192.99,-155.49 210.28,-148.16 225.22,-141.83\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"226.29,-144.75 234.13,-137.63 223.56,-138.31 226.29,-144.75\"/>\n</g>\n<!-- Polymorphism -->\n<g id=\"node21\" class=\"node\">\n<title>Polymorphism</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-67.8\" font-family=\"Times,serif\" font-size=\"14.00\">Polymorphism</text>\n</g>\n<!-- Polymorphic&#45;&gt;Polymorphism -->\n<g id=\"edge21\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Polymorphism</title>\n<path fill=\"none\" stroke=\"black\" d=\"M149.96,-162.11C164.98,-144.65 189.51,-118.01 214.33,-99 215.77,-97.9 217.26,-96.81 218.79,-95.74\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"220.34,-98.26 226.8,-89.86 216.51,-92.39 220.34,-98.26\"/>\n</g>\n<!-- Structure -->\n<g id=\"node22\" class=\"node\">\n<title>Structure</title>\n<text text-anchor=\"middle\" x=\"263.56\" y=\"-13.8\" font-family=\"Times,serif\" font-size=\"14.00\">Structure</text>\n</g>\n<!-- Polymorphic&#45;&gt;Structure -->\n<g id=\"edge22\" class=\"edge\">\n<title>Polymorphic&#45;&gt;Structure</title>\n<path fill=\"none\" stroke=\"black\" d=\"M141.96,-162.28C153.35,-134.43 178.63,-80 214.33,-45 216.48,-42.89 218.83,-40.89 221.3,-39.01\"/>\n<polygon fill=\"black\" stroke=\"black\" points=\"222.73,-41.59 229.02,-33.06 218.79,-35.81 222.73,-41.59\"/>\n</g>\n</g>\n</svg>\n"
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "ma",
        "story": []
      },
      "date": 1660287096845
    },
    {
      "item": {
        "type": "factory",
        "id": "50fc05ed81a0a470"
      },
      "id": "50fc05ed81a0a470",
      "type": "add",
      "date": 1660287101583
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is messaging — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word [[ma]] — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —Alan Kay"
      },
      "date": 1660287109618
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is messaging — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1660287128848
    },
    {
      "item": {
        "type": "factory",
        "id": "c0664eeabe8356d3"
      },
      "id": "c0664eeabe8356d3",
      "type": "add",
      "after": "50fc05ed81a0a470",
      "date": 1702404111491
    },
    {
      "type": "edit",
      "id": "c0664eeabe8356d3",
      "item": {
        "type": "pagefold",
        "id": "c0664eeabe8356d3",
        "text": "~"
      },
      "date": 1702404114515
    },
    {
      "item": {
        "type": "factory",
        "id": "5e945643184c13f5"
      },
      "id": "5e945643184c13f5",
      "type": "add",
      "after": "c0664eeabe8356d3",
      "date": 1702404115882
    },
    {
      "type": "edit",
      "id": "5e945643184c13f5",
      "item": {
        "type": "reference",
        "id": "5e945643184c13f5",
        "site": "thompson.forage.ustawi.wiki",
        "slug": "the-space-between",
        "title": "The Space Between",
        "text": "Phil Jackson, the renown basketball coach – Michael Jordon's coach – would tell his players on the court to always look for the space between."
      },
      "date": 1702404123980
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is [[Messaging]] — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702404340867
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1702404360844
    },
    {
      "item": {
        "type": "factory",
        "id": "e2bdda6d0fade784"
      },
      "id": "e2bdda6d0fade784",
      "type": "add",
      "after": "5e945643184c13f5",
      "date": 1702404530672
    },
    {
      "type": "edit",
      "id": "e2bdda6d0fade784",
      "item": {
        "type": "reference",
        "id": "e2bdda6d0fade784",
        "site": "splash.fed.wiki.org",
        "slug": "messaging",
        "title": "Messaging",
        "text": "Communication and collaboration is based upon exchange of polymorphic messages rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
      },
      "date": 1702404535030
    },
    {
      "id": "e2bdda6d0fade784",
      "type": "move",
      "order": [
        "50fc05ed81a0a470",
        "c0664eeabe8356d3",
        "e2bdda6d0fade784",
        "5e945643184c13f5"
      ],
      "date": 1702404539816
    },
    {
      "type": "edit",
      "id": "e2bdda6d0fade784",
      "item": {
        "type": "reference",
        "id": "e2bdda6d0fade784",
        "site": "splash.fed.wiki.org",
        "slug": "messaging",
        "title": "Messaging",
        "text": "Communication and collaboration is based upon exchange of [[Polymorphic]] [[Messages]] rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
      },
      "date": 1702404889034
    },
    {
      "item": {
        "type": "factory",
        "id": "dbdc2635b2664ce7"
      },
      "id": "dbdc2635b2664ce7",
      "type": "add",
      "after": "5e945643184c13f5",
      "date": 1702404902282
    },
    {
      "type": "edit",
      "id": "dbdc2635b2664ce7",
      "item": {
        "type": "graphviz",
        "id": "dbdc2635b2664ce7",
        "text": "DOT FROM two-level-diagrams"
      },
      "date": 1702404914462
    },
    {
      "type": "edit",
      "id": "dbdc2635b2664ce7",
      "item": {
        "type": "graphviz",
        "id": "dbdc2635b2664ce7",
        "text": "DOT FROM two-level-diagram"
      },
      "date": 1702404932163
    },
    {
      "type": "fork",
      "site": "wiki.ralfbarkow.ch",
      "date": 1702405093183
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is Messaging — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702405949990
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "paragraph",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **messaging** — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702405986212
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "markdown",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **messaging** — that is what the kernal of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702405989478
    },
    {
      "type": "edit",
      "id": "e2bdda6d0fade784",
      "item": {
        "type": "reference",
        "id": "e2bdda6d0fade784",
        "site": "splash.fed.wiki.org",
        "slug": "messaging",
        "title": "Messaging",
        "text": "Communication and collaboration is based upon exchange of [[Polymorphic]] messages rather than exchange of \"executable\" code (DNA/RNA in the case of biological cells, machine code in the case of computing."
      },
      "date": 1702406013526
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "markdown",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **messaging** — that is what the kernel of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1702406204026
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1702406302876
    },
    {
      "type": "edit",
      "id": "50fc05ed81a0a470",
      "item": {
        "type": "markdown",
        "id": "50fc05ed81a0a470",
        "text": "“The big idea is **[[Messaging]]** — that is what the kernel of Smalltalk/Squeak is all about (and it’s something that was never quite completed in our Xerox PARC phase). The Japanese have a small word ma — for that which is in between perhaps the nearest English equivalent is [[interstitial]]. The key in making great and growable systems is much more to design how its modules communicate rather than what their internal properties and behaviors should be.” —[[Alan Kay]]"
      },
      "date": 1707116282976
    },
    {
      "type": "fork",
      "site": "localhost:3000",
      "date": 1707118599294
    }
  ]
}