{
  "title": "Resource",
  "story": [
    {
      "type": "reference",
      "id": "e8d6b21302437581",
      "site": "wiki.ralfbarkow.ch",
      "slug": "para-method",
      "title": "PARA Method",
      "text": "A [[Project]] is “a series of [[Task]]s linked to a [[Goal]], with a [[Deadline]].” [https://fortelabs.com/blog/para/ blog]"
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "Resource",
        "story": []
      },
      "date": 1675226611013
    },
    {
      "item": {
        "type": "factory",
        "id": "e8d6b21302437581"
      },
      "id": "e8d6b21302437581",
      "type": "add",
      "date": 1675226613671
    },
    {
      "type": "edit",
      "id": "e8d6b21302437581",
      "item": {
        "type": "reference",
        "id": "e8d6b21302437581",
        "site": "wiki.ralfbarkow.ch",
        "slug": "para-method",
        "title": "PARA Method",
        "text": "A [[Project]] is “a series of [[Task]]s linked to a [[Goal]], with a [[Deadline]].” [https://fortelabs.com/blog/para/ blog]"
      },
      "date": 1675226616349
    }
  ]
}