{
  "title": "Verse",
  "story": [
    {
      "type": "reference",
      "id": "60cf763ee66ca771",
      "site": "wiki.ralfbarkow.ch",
      "slug": "write-wiki-pages-in-a-poetic-form",
      "title": "Write Wiki Pages in a Poetic Form",
      "text": "\"What would it mean to [[write]] wiki pages in a poetic form, inspired by [[Richard Gabriel]]'s [[Haiku]] practice? Can other people feel the delightful unfolding that [[I]] feel?\" [https://matrix.to/#/!ORfrUEFeWFcHAMLFLr:matrix.org/%24169074029828042PfEtk%3Amatrix.org matrix] (2023-07-30-Sunday-Explorers-with-Thompson.txt, 09:29:45 From Jeff Miller To Everyone)"
    },
    {
      "type": "paragraph",
      "id": "5f510f91e5110c63",
      "text": "⇒ [[Vers]]"
    }
  ],
  "journal": [
    {
      "type": "create",
      "item": {
        "title": "Verse",
        "story": []
      },
      "date": 1692276163621
    },
    {
      "item": {
        "type": "factory",
        "id": "60cf763ee66ca771"
      },
      "id": "60cf763ee66ca771",
      "type": "add",
      "date": 1692276166497
    },
    {
      "type": "edit",
      "id": "60cf763ee66ca771",
      "item": {
        "type": "reference",
        "id": "60cf763ee66ca771",
        "site": "wiki.ralfbarkow.ch",
        "slug": "write-wiki-pages-in-a-poetic-form",
        "title": "Write Wiki Pages in a Poetic Form",
        "text": "\"What would it mean to [[write]] wiki pages in a poetic form, inspired by [[Richard Gabriel]]'s [[Haiku]] practice? Can other people feel the delightful unfolding that [[I]] feel?\" [https://matrix.to/#/!ORfrUEFeWFcHAMLFLr:matrix.org/%24169074029828042PfEtk%3Amatrix.org matrix] (2023-07-30-Sunday-Explorers-with-Thompson.txt, 09:29:45 From Jeff Miller To Everyone)"
      },
      "date": 1692276168659
    },
    {
      "item": {
        "type": "factory",
        "id": "5f510f91e5110c63"
      },
      "id": "5f510f91e5110c63",
      "type": "add",
      "after": "60cf763ee66ca771",
      "date": 1692276183327
    },
    {
      "type": "edit",
      "id": "5f510f91e5110c63",
      "item": {
        "type": "paragraph",
        "id": "5f510f91e5110c63",
        "text": "⇒ [[Vers]"
      },
      "date": 1692276185066
    },
    {
      "type": "edit",
      "id": "5f510f91e5110c63",
      "item": {
        "type": "paragraph",
        "id": "5f510f91e5110c63",
        "text": "⇒ [[Vers]]"
      },
      "date": 1692276202559
    }
  ]
}